name: buildEnv_runPython


on:
  schedule:
    - cron: '0 0 * * *'  # 每天的第0小时运行

    
  workflow_dispatch:  # 支持手动触发

  
  # push:
  #   branches:
  #     - main  # 每次push到main分支时触发


jobs:
  buildEnv_runPython:
    runs-on: ubuntu-latest
    steps:


      - name: Test Domain Access
        run: |
          echo "Testing domain accessibility..."
          curl -I "https://xn--cp3a08l.com" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" \
            -H "Accept-Language: en-US,en;q=0.9" \
            -H "Accept-Encoding: gzip, deflate, br" \
            -H "Cache-Control: max-age=0" \
            -H "Sec-CH-UA: \"Chromium\";v=\"121\", \"Google Chrome\";v=\"121\", \"Not A(Brand\";v=\"99\"" \
            -H "Sec-CH-UA-Mobile: ?0" \
            -H "Sec-CH-UA-Platform: \"Windows\"" \
            -H "Sec-Fetch-Site: none" \
            -H "Sec-Fetch-Mode: navigate" \
            -H "Sec-Fetch-User: ?1" \
            -H "Sec-Fetch-Dest: document" \
            -H "Connection: keep-alive"


      # 新增：检查网络环境步骤
      - name: Check Network Environment
        run: |
          echo "============= Network Environment Check ============="
          echo "Current Time (UTC): $(date -u '+%Y-%m-%D %H:%M:%S')"
          
          echo -e "\n=== Current IP Address ==="
          curl -s ip.sb
          
          echo -e "\n=== IP Location Details ==="
          curl -s ipinfo.io | jq .
          
          echo -e "\n=== IP Geographic Info ==="
          curl -s http://ip-api.com/json | jq .

          
          # echo -e "\n=== Network Speed Test ==="
          # curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -

   
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml


      - name: Extract and run subconverter
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # 设置环境变量
        run: |
          curl -L -o subconverter_linux64.tar.gz $(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PERSONAL_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/asdlokj1qpi233/subconverter/releases/latest | grep "browser_download_url" | grep "linux64[.]tar" | cut -d '"' -f 4)
          tar xzf subconverter_linux64.tar.gz
          chmod +x subconverter/subconverter
          nohup subconverter/subconverter &


      - name: runrun python
        env:

        
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ACCOUNT_API_TOKEN: ${{ secrets.CF_ACCOUNT_API_TOKEN }}
          CF_KV_ID: ${{ secrets.CF_KV_ID }}
          CONVERT_PARAM: ${{ secrets.CONVERT_PARAM }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GIST_ID: ${{ secrets.GIST_ID }}


        run: python converter_push.py

