name: buildEnv_runPython


on:
  schedule:
    - cron: '0 0 * * *'  # 每天的第0小时运行

    
  workflow_dispatch:  # 支持手动触发

  
  # push:
  #   branches:
  #     - main  # 每次push到main分支时触发


jobs:
  buildEnv_runPython:
    runs-on: ubuntu-latest
    steps:


      # 新增：检查网络环境步骤
      - name: Check Network Environment
        run: |
          echo "============= Network Environment Check ============="
          echo "Current Time (UTC): $(date -u '+%Y-%m-%D %H:%M:%S')"
          
          echo -e "\n=== Current IP Address ==="
          curl -s ip.sb
          
          echo -e "\n=== IP Location Details ==="
          curl -s ipinfo.io | jq .
          
          echo -e "\n=== IP Geographic Info ==="
          curl -s http://ip-api.com/json | jq .
          
          echo -e "\n=== Testing Connection to Chinese Websites ==="
          echo "Testing Baidu.com:"
          curl -I -m 10 -o /dev/null -s -w "Baidu Response: %{http_code}\n" http://baidu.com
          echo "Testing Alibaba.com:"
          curl -I -m 10 -o /dev/null -s -w "Alibaba Response: %{http_code}\n" http://alibaba.com
          
          echo -e "\n=== Network Route to Baidu ==="
          traceroute -m 10 baidu.com || true
          
          echo -e "\n=== Network Speed Test ==="
          curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -

    
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml


      - name: Extract and run subconverter
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # 设置环境变量
        run: |
          curl -L -o subconverter_linux64.tar.gz $(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PERSONAL_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/asdlokj1qpi233/subconverter/releases/latest | grep "browser_download_url" | grep "linux64[.]tar" | cut -d '"' -f 4)
          tar xzf subconverter_linux64.tar.gz
          chmod +x subconverter/subconverter
          nohup subconverter/subconverter &


      - name: runrun python
        env:

        
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ACCOUNT_API_TOKEN: ${{ secrets.CF_ACCOUNT_API_TOKEN }}
          CF_KV_ID: ${{ secrets.CF_KV_ID }}
          CONVERT_PARAM: ${{ secrets.CONVERT_PARAM }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GIST_ID: ${{ secrets.GIST_ID }}


        run: python converter_push.py

