name: Subconverter TO CF KV

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每3天的午夜（UTC时间）触发
  workflow_dispatch:  # 支持手动触发

jobs:
  run-subconverter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download and Setup Subconverter
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        echo "Downloading subconverter..."
        # 先获取下载 URL
        DOWNLOAD_URL=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $PERSONAL_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/asdlokj1qpi233/subconverter/releases/latest" | \
          grep "browser_download_url.*linux64.tar.gz" | \
          cut -d '"' -f 4)
        
        echo "Download URL: $DOWNLOAD_URL"
        
        if [ -z "$DOWNLOAD_URL" ]; then
          echo "Error: Could not get download URL"
          exit 1
        fi
        
        # 下载文件
        curl -L -o subconverter_linux64.tar.gz "$DOWNLOAD_URL"
        
        echo "Extracting subconverter..."
        tar xzf subconverter_linux64.tar.gz
        chmod +x subconverter/subconverter
        
        echo "Starting subconverter in background with logging..."
        cd subconverter
        # 创建日志目录
        mkdir -p logs
        
        # 启动 subconverter 并记录日志
        ./subconverter -f > logs/subconverter.log 2>&1 &
        
        echo "Waiting for subconverter to start..."
        sleep 5
        
        # 显示初始日志
        echo "=== Initial subconverter log content ==="
        tail -n 50 logs/subconverter.log
        
        # 检查进程
        if pgrep subconverter > /dev/null; then
          echo "✅ Subconverter is running successfully"
        else
          echo "❌ ERROR: Subconverter failed to start"
          cat logs/subconverter.log
          exit 1
        fi

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run Conversion Script
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_KV_ID: ${{ secrets.CF_KV_ID }}
        CF_ACCOUNT_API_TOKEN: ${{ secrets.CF_ACCOUNT_API_TOKEN }}
        CONVERT_PARAM: ${{ secrets.CONVERT_PARAM }}
      run: |
        echo "Starting conversion process..."
        python converter_push.py
        
        echo "=== Final subconverter logs ==="
        tail -n 100 subconverter/logs/subconverter.log
        
        # 检查最终状态
        if pgrep subconverter > /dev/null; then
          echo "✅ Subconverter is still running"
        else
          echo "⚠️ WARNING: Subconverter process has ended"
        fi

    - name: Upload Subconverter Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: subconverter-logs
        path: subconverter/logs/
        retention-days: 5
