name: Subconverter TO CF KV

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每3天的午夜（UTC时间）触发
  workflow_dispatch:  # 支持手动触发

jobs:
  run-subconverter:
    runs-on: windows-latest  # 改为 windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download and Setup Subconverter
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      shell: pwsh  # 使用 PowerShell
      run: |
        Write-Host "Downloading subconverter..."
        # 获取下载 URL
        $headers = @{
          "Accept" = "application/vnd.github+json"
          "Authorization" = "Bearer $env:PERSONAL_TOKEN"
          "X-GitHub-Api-Version" = "2022-11-28"
        }
        
        $response = Invoke-RestMethod -Uri "https://api.github.com/repos/asdlokj1qpi233/subconverter/releases/latest" -Headers $headers
        $downloadUrl = $response.assets | Where-Object { $_.name -like "*windows64.zip" } | Select-Object -ExpandProperty browser_download_url
        
        Write-Host "Download URL: $downloadUrl"
        
        if (-not $downloadUrl) {
          Write-Host "Error: Could not get download URL"
          exit 1
        }
        
        # 下载文件
        Invoke-WebRequest -Uri $downloadUrl -OutFile "subconverter_windows64.zip"
        
        Write-Host "Extracting subconverter..."
        Expand-Archive -Path "subconverter_windows64.zip" -DestinationPath "subconverter"
        
        Write-Host "Starting subconverter in background with logging..."
        cd subconverter
        # 创建日志目录
        New-Item -ItemType Directory -Force -Path "logs"
        
        # 启动 subconverter（Windows 方式）
        Start-Process -FilePath ".\subconverter.exe" -ArgumentList "-f", "--skip-cert-verify", "--cache", "--log-level", "verbose" -RedirectStandardOutput "logs\subconverter.log" -RedirectStandardError "logs\subconverter_error.log"
        
        Write-Host "Waiting for subconverter to start..."
        Start-Sleep -Seconds 10
        
        # 显示初始日志
        Write-Host "=== Initial subconverter log content ==="
        Get-Content -Tail 50 "logs\subconverter.log"
        
        # 检查进程
        $process = Get-Process subconverter -ErrorAction SilentlyContinue
        if ($process) {
          Write-Host "✅ Subconverter is running successfully"
          $process | Select-Object Id, ProcessName, CPU, WorkingSet
        } else {
          Write-Host "❌ ERROR: Subconverter failed to start"
          Get-Content "logs\subconverter.log"
          Get-Content "logs\subconverter_error.log"
          exit 1
        }

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run Conversion Script
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_KV_ID: ${{ secrets.CF_KV_ID }}
        CF_ACCOUNT_API_TOKEN: ${{ secrets.CF_ACCOUNT_API_TOKEN }}
        CONVERT_PARAM: ${{ secrets.CONVERT_PARAM }}
      shell: pwsh  # 使用 PowerShell
      run: |
        Write-Host "Starting conversion process..."
        python converter_push.py
        
        Write-Host "=== Final subconverter logs ==="
        Get-Content -Tail 100 "subconverter\logs\subconverter.log"
        
        # 检查最终状态
        $process = Get-Process subconverter -ErrorAction SilentlyContinue
        if ($process) {
          Write-Host "✅ Subconverter is still running"
          $process | Select-Object Id, ProcessName, CPU, WorkingSet
        } else {
          Write-Host "⚠️ WARNING: Subconverter process has ended"
        }

    - name: Upload Subconverter Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: subconverter-logs
        path: subconverter/logs/
        retention-days: 5
