name: subconverter;push_kv

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时更新一次
  workflow_dispatch:  # 支持手动触发
  push:
    branches:
      - main  # 每次push到main分支时触发

env:
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_NAMESPACE_ID: ${{ secrets.CF_NAMESPACE_ID }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  SUBSCRIPTION_URL: ${{ secrets.SUBSCRIPTION_URL }}
  CONVERT_PARAM: ${{ secrets.CONVERT_PARAM }}
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

jobs:
  upupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Extract and run subconverter
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # 设置环境变量
        run: |
          curl -L -o subconverter_linux64.tar.gz $(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PERSONAL_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/tindy2013/subconverter/releases/latest | grep "browser_download_url" | grep "linux64[.]tar" | cut -d '"' -f 4)
          tar xzf subconverter_linux64.tar.gz
          chmod +x subconverter/subconverter
          nohup subconverter/subconverter &

      - name: python:update_cf_kv
        run: |
          python update_cf_kv.py
          python update.py
